### ISSUE TITLE
Please add OSS license

### ISSUE THREAD

**Issue by bwehrle** [shibataka000/virtual-service-route-controller#1]
Hi,
This operator solves a problem I've been wanting to solve.  If you're open to sharing it with an OSS license, it would be really useful. 
Sincerely,
Brian

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by shibataka000** [comment]
Hi @bwehrle

I'm glad to hear this repository help you.

I added OSS license in #2 .

> [!WARNING]
> I created this operator for only my study about custom controller. I'm sorry but I will not maintain this. If you want to develop and maintain this, you can fork this.

Sincerely,
Takao

**Comment by bwehrle** [comment]
Thank you!
